apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    bot-token: ENC[AES256_GCM,data:YBgURF9s86G6KvyLazSBHMHdgpjfRGXqn3gJ0l7YGozxcUXyAaNaG/uXqiXHBg==,iv:fLL3P55aBf2xPf+qXleaNMclsq25jrGzdl3IZkrMSRc=,tag:xs0CZ4bd56tJVWdPVb1p/Q==,type:str]
    chat-id: ENC[AES256_GCM,data:5wftflUXw8rKJ9M=,iv:LyjRa8QE9Z22kgzS+9i2XQBuJnbWEKGFbdLD+b+oads=,tag:QZOPUjzA6ds5zto9rn1CeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaHlOTkwwM3hzbjQvdDFP
            Q1N0M21pYzJzTFVWMWcxRWcvTWg5dUJ3bTBvCjNxclo3L2xJZXM2QUdWR1Q2ajli
            ekRoV0pDbHArMktDcXhpM0txYkZJTnMKLS0tIGI0UDF1Z3p2MGUxVmdQankzYXNx
            cVMrOWdKNEVpOFU2T0VwNUFaUjVaS0UKX6mvJQh013n/gusENDYHBW4LJ8+ziI5P
            ftbqkNU48YvgEzSURzo3UKz7abqkhc49LFxk46r+woL+KFB9Bzr7zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ucjp64s2czgpcfx2adte56fku75d84pwhesnd2wgvnnz46v02euqww5gqw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T17:19:49Z"
    mac: ENC[AES256_GCM,data:eG+8l7wcLiEWhFLcWptdUyETp14OYEBedzSS/bCWtDJ+VHwhnTPvBFbfrtJrHjZHDOxGbBJHryUQkISR66BbIpnXo38GOv87bmR6F6JCZq8QW7RNz+9BqfmjqphZiUMw8wM8aglKi6hcpn7r24TSHa79n8aUbjSWlogU5kmqPnk=,iv:R3GXdiZzMLs4ic6ieCg+dkC6cmQsmixedJJDcY9ARyI=,tag:rFXKUASyE0jaJ+8a+lqr3w==,type:str]
    version: 3.13.3
