apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:hd2DarxP9vgP1A==,iv:aQQbnaoAx3mYvjNjrcFvNkosUU5V27/woonQIifSnfU=,tag:hIzbOiu33LGDN9mWe06c3A==,type:str]
    admin-password: ENC[AES256_GCM,data:f91VsXaCpEiAr3+3+afod9bwt3/yjJoETmXEPA==,iv:/6vHzIfYPtTrXgofMS5fA/qDyH1gqhFvrpLyXYf3pWM=,tag:DwN5hjLiG0l/jo1Q7ogADQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYWtRSGhTcFc2bG9vOVpJ
            RjR6QmFUWUdzcEFIWGhTYzFxeTFyb05nUFYwCm1SUkxhVmczdVJkY0dqRTlnZzFr
            dXZkUE1YTmo1VlJmcjgwdlltRkdVazgKLS0tIHk5QTZCR1BwOFZsWGpOVHNiQTFY
            eUJQUUMzVHBCR0d5Q1NmK3REUllHcHMK5f7hLiy719yLoMXqvpb8Jsnic/CdEcFc
            CI5+tJJa6ZpUHF7lGrWotzR/6AjsaIW7rFUrlBi1UJTWs6dixI2LSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ucjp64s2czgpcfx2adte56fku75d84pwhesnd2wgvnnz46v02euqww5gqw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T21:26:51Z"
    mac: ENC[AES256_GCM,data:xwEQzoD4cBdXIDHHp1/dkHfESYhkk/U6APAy8w8nMeioTOw2GmCZqm0os9utxi/N8JVqQmbNxSDf2QQEAWd+60a6mkEiIPXLovH2FHWCj7XMbzyRB9s/YLbyLvJwJxT/LaT6ltY6NSTJGp8hXv+K75yJaGMkKXG31bI0blbx2Fg=,iv:B75kHlLrexONJvohQH0gRIMC/vicm5MSLo+VfiQ2DOo=,tag:gw3/mPhAvL1lAax0UOJ2NA==,type:str]
    version: 3.13.3
