apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - grafana-admin.sops.yaml
  - grafana-tailnet.sops.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: grafana-dashboard-plex
    namespace: monitoring
    files:
      - media-server.json=dashboards/media-server.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
