# docker stack deploy --compose-file docker-compose.goping.yml goping
services:
  server:
    image: ghcr.io/alexraskin/goping:${GIT_COMMIT_HASH:-latest}
    networks:
      - metrics
    deploy:
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    secrets:
      - webhook_url
    environment:
      - WEBHOOK_URL=/run/secrets/webhook_url

secrets:
  webhook_url:
    external: true

networks:
  metrics:
    external: true
    name: metrics
    driver: overlay
