#   cp backup-oci.example.yaml backup-oci.sops.yaml
#   $EDITOR backup-oci.sops.yaml
#   cd apps && mise exec -- sops --encrypt --in-place base/cnpg/cluster/backup-oci.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-oci
  namespace: cnpg-system
type: Opaque
stringData:
  access-key-id: PASTE_ACCESS_KEY_ID_HERE
  secret-access-key: PASTE_SECRET_ACCESS_KEY_HERE
  region: PASTE_OCI_REGION_HERE
