apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cnpg-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 90Gi
    storageClass: db-local

  postgresql:
    parameters:
      shared_buffers: 512MB
      effective_cache_size: 1536MB
      work_mem: 8MB
      maintenance_work_mem: 128MB
      max_connections: "200"

  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 2Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      dedicated: database
    tolerations:
      - key: dedicated
        operator: Equal
        value: database
        effect: NoSchedule

  monitoring:
    enablePodMonitor: true
