apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cnpg-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 90Gi
    storageClass: db-local

  managed:
    roles:
      - name: gatus
        ensure: present
        login: true
        passwordSecret:
          name: gatus-db
      - name: grafana
        ensure: present
        login: true
        passwordSecret:
          name: grafana-db
  env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required

  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/
      endpointURL: https://axzx7yxanbks.compat.objectstorage.us-phoenix-1.oraclecloud.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-oci
          key: access-key-id
        secretAccessKey:
          name: cnpg-backup-oci
          key: secret-access-key
        region:
          name: cnpg-backup-oci
          key: region
      data:
        compression: gzip
        jobs: 2
      wal:
        compression: gzip
        maxParallel: 2

  postgresql:
    parameters:
      shared_buffers: 512MB
      effective_cache_size: 1536MB
      work_mem: 8MB
      maintenance_work_mem: 128MB
      max_connections: "200"

  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 2Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      dedicated: database
    tolerations:
      - key: dedicated
        operator: Equal
        value: database
        effect: NoSchedule

  monitoring:
    enablePodMonitor: true
