# docker stack deploy --compose-file docker-compose.excuses.yml excuses --with-registry-auth
services:
  app:
    image: ghcr.io/alexraskin/dev-excuses:${GIT_COMMIT_HASH:-latest}
    networks:
      - proxy
    deploy:
      labels:
        - "tunnel.enabled=true"
        - "tunnel.port=8000"
        - "tunnel.hostname=sorry.alexraskin.com"
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy