apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cluster-subnet-router
spec:
  tags:
    - tag:k8s-router
  hostname: talos-subnet-router
  subnetRouter:
    advertiseRoutes:
      - 10.0.200.0/24
