# docker stack deploy --compose-file docker-compose.swarmctl.yml swarmctl
services:
  server:
    image: ghcr.io/alexraskin/swarmctl:${GIT_COMMIT_HASH:-latest}
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - swarmctl-auth-token
      - cloudflare-email
      - cloudflare-account-id
      - cloudflare-api-key
      - cloudflare-tunnel-id
      - pushover-api-key
      - pushover-recipient
    environment:
      - AUTH_TOKEN=/run/secrets/swarmctl-auth-token
      - CLOUDFLARE_API_EMAIL=/run/secrets/cloudflare-email
      - CLOUDFLARE_API_KEY=/run/secrets/cloudflare-api-key
      - CLOUDFLARE_ACCOUNT_ID=/run/secrets/cloudflare-account-id
      - CLOUDFLARE_TUNNEL_ID=/run/secrets/cloudflare-tunnel-id
      - PUSHOVER_API_KEY=/run/secrets/pushover-api-key
      - PUSHOVER_RECIPIENT=/run/secrets/pushover-recipient
    deploy:
      labels:
        - "tunnel.enabled=true"
        - "tunnel.port=9000"
        - "tunnel.hostname=swarmctl.alexraskin.com"
      placement:
        constraints:
          - node.role == manager
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy

secrets:
  swarmctl-auth-token:
    external: true
  cloudflare-email:
    external: true
  cloudflare-account-id:
    external: true
  cloudflare-api-key:
    external: true
  cloudflare-tunnel-id:
    external: true
  pushover-api-key:
    external: true
  pushover-recipient:
    external: true
