# docker stack deploy --compose-file docker-compose.swarmctl.yml swarmctl
services:
  server:
    image: ghcr.io/alexraskin/swarmctl:${GIT_COMMIT_HASH:-latest}
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - swarmctl-auth-token
    environment:
      - AUTH_TOKEN=/run/secrets/swarmctl-auth-token
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy

secrets:
  swarmctl-auth-token:
    external: true