# docker stack deploy --compose-file docker-compose.robo.yml robotwizy --with-registry-auth
services:
  bot:
    image: ghcr.io/alexraskin/robotwizy:${GIT_COMMIT_HASH:-latest}
    volumes:
      - type: bind
        source: /mnt/robotwizy/config.toml
        target: /app/config.toml
    deploy:
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
