global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'watchtower'
    metrics_path: /v1/metrics
    bearer_token: ${WATCHTOWER_TOKEN}
    static_configs:
      - targets:
        - '10.0.200.87:9000'
  
  - job_name: 'swarmctl'
    metrics_path: /metrics
    bearer_token: ${SWARMCTL_TOKEN}
    dns_sd_configs:
      - names:
          - 'tasks.swarmctl_server'
        type: 'A'
        port: 9000

  - job_name: 'goping'
    dns_sd_configs:
      - names:
        - 'tasks.goping_server'
        type: 'A'
        port: 8080