# docker stack deploy --compose-file docker-compose.lhbotgo.yml lhbotgo --with-registry-auth
services:
  app:
    image: ghcr.io/alexraskin/lhbotgo:${GIT_COMMIT_HASH:-latest}
    networks:
      - database
    volumes:
      - type: bind
        source: /mnt/lhbotgo/config.toml
        target: /var/lib/config.toml
    deploy:
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  database:
    external: true
