# docker stack deploy --compose-file docker-compose.gopaste.yml gopaste --with-registry-auth
services:
  web:
    image: ghcr.io/alexraskin/gopaste:${GIT_COMMIT_HASH:-latest}
    deploy:
      labels:
        - "tunnel.port=7000"
        - "tunnel.hostname=paste.alexraskin.com"
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    volumes:
      - type: bind
        source: /mnt/gopaste
        target: /db
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy