services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/.docker/config.json:/config.json
        command: --http-api-update --http-api-metrics --cleanup
        env_file:
            - conf.env
        networks:
            - proxy

networks:
    proxy:
        external: true