services:
  db:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8089:8089/udp"
    networks:
      - metrics
    volumes:
      - "/var/lib/influx:/var/lib/influxdb2"  
    mem_limit: 128m
    cpus: 0.1
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  metrics:
    external: true