# docker stack deploy --compose-file docker-compose.influx.yml influx
services:
  db:
    image: influxdb
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - database
      - internal
    volumes:
      - type: bind
        source: /mnt/influxdb/data
        target: /var/lib/influxdb2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M

networks:
  database:
    external: true
  internal:
    external: true
