# docker stack deploy --compose-file docker-compose.alexraskin.yml alexraskin
services:
  web:
    image: ghcr.io/alexraskin/alexraskin.com:${GIT_COMMIT_HASH:-latest}
    networks:
      - proxy
    deploy:
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy