# docker stack deploy --compose-file docker-compose.alexraskin.yml alexraskin
services:
  web:
    image: ghcr.io/alexraskin/alexraskin.com:${GIT_COMMIT_HASH:-latest}
    networks:
      - proxy
    deploy:
      labels:
        - "cloudflared.tunnel.enabled=true"
        - "cloudflared.tunnel.port=8000"
        - "cloudflared.tunnel.0.hostname=alexraskin.com"
        - "cloudflared.tunnel.1.hostname=www.alexraskin.com"
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy
