# docker stack deploy --compose-file docker-compose.urls.yml vanityurls
services:
  web:
    image: ghcr.io/alexraskin/go-vanityurls:de03d3e9b417b1e3f7bbae3ab663f8050bc0a7fa
    networks:
      - proxy
    deploy:
      labels:
        - "tunnel.port=8080"
        - "tunnel.hostname=go.alexraskin.com"
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy