apiVersion: v1
kind: Service
metadata:
  name: cloud-edge-egress
  namespace: gatus
  annotations:
    tailscale.com/tailnet-ip: "100.79.150.123"
spec:
  type: ExternalName
  externalName: placeholder
---
apiVersion: v1
kind: Service
metadata:
  name: chronos-egress
  namespace: gatus
  annotations:
    tailscale.com/tailnet-ip: "100.109.167.97"
spec:
  type: ExternalName
  externalName: placeholder
