apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatus-probe
  namespace: gatus
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: gatus-probe-token
  namespace: gatus
  annotations:
    kubernetes.io/service-account.name: gatus-probe
type: kubernetes.io/service-account-token
