apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: alexraskin-com
  namespace: flux-system
spec:
  image: ghcr.io/alexraskin/alexraskin.com
  interval: 72h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: alexraskin-com
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: alexraskin-com
  filterTags:
    pattern: '^v?(?P<version>\d+\.\d+\.\d+)$'
    extract: '$version'
  policy:
    semver:
      range: '>=0.1.0'
