apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 72h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(images): {{ range .Changed.Changes }}{{ .OldValue }} -> {{ .NewValue }} {{ end }}

        Pushed by image-automation-controller.
    push:
      branch: main
  update:
    path: ./apps/base
    strategy: Setters
