# docker stack deploy --compose-file docker-compose.filego.yml filego --with-registry-auth
services:
  app:
    image: ghcr.io/alexraskin/filego:${GIT_COMMIT_HASH:-latest}
    networks:
      - proxy
      - storage
    volumes:
      - type: bind
        source: /mnt/filego/config.toml
        target: /var/lib/filego/config.toml
    deploy:
      labels:
        - "cloudflared.tunnel.enabled=true"
        - "cloudflared.tunnel.port=8080"
        - "cloudflared.tunnel.0.hostname=filego.alexraskin.com"
        - "cloudflared.tunnel.1.hostname=elx.sh"
        - "cloudflared.tunnel.2.hostname=www.elx.sh"
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy
  storage:
    external: true
