# docker stack deploy --compose-file docker-compose.tunnel.yml cloudflared
services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    env_file: tunnel.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
networks:
  proxy:
    external: true
