# docker stack deploy --compose-file docker-compose.tunnel.yml cloudflared
services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/cloudflare_token
    secrets:
      - cloudflare_token
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

secrets:
  cloudflare_token:
    external: true

networks:
  proxy:
    external: true
