apiVersion: v1
kind: Secret
metadata:
    name: pve-exporter
    namespace: monitoring
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:sAI81S4R7d7nR9xpc5c=,iv:RRj4GZZJbqiiaWUaZLKASloZPlnwmjI/vJwKh/xe174=,tag:2hP6K70LZ5TcWjrk8yk0+A==,type:str]
    token-name: ENC[AES256_GCM,data:5KIFj3adMf4=,iv:p6GiqUki33+OSq/fnXbrs9amu8S80C40PPyUY9Ivqi8=,tag:ufOY7Kh0TkrUwxsLyEYhmA==,type:str]
    token-value: ENC[AES256_GCM,data:VHLxWJ10hOcc9x516UsKRKFwsqdCmoiVWwk2Op/Asp3Vpvq8,iv:67SZQO3B+HTGdel4JsS7krQEls3jW3IJtNkO1VSi31k=,tag:TMjBm0bgjkY4Iv5VLeoKtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVWsySk84NXpIUk5aamxz
            M2JiMkR0YWdQYnl1Q0doWXB0bGFrb1IyanpjClM5Uys2RXhlMFd1cS94SFlBT2dQ
            VGlzRFc5T2F6UnlkQmh3ZGh5WkMzc1kKLS0tIDVSUER5RzFWY3k0b3NucjQ3a0gy
            Y0dYUDZyVm9jcFN6V3lBVHJPSlNQb0EKAeWKyKiMIbYL+8fUsEwIjUmlmycNTLJC
            0fe4UQMPZw7HVDt8UNrQeSc1VvTE4j4gQcEcjZ3MFd+hzJFMYDMRMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ucjp64s2czgpcfx2adte56fku75d84pwhesnd2wgvnnz46v02euqww5gqw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T16:34:02Z"
    mac: ENC[AES256_GCM,data:ow/Qga2qUPpbli7HYjPAW05xG82r97XekwJ7Fl0tQjTk6T/95NKy8Zb4EFSjR4WiwhiErtEk7bHN7nuKLhqeN89824JJM+rfbbvUSF97AQRGCdNtJxpL6JO+0Q+ZHLUkPkFVcaY4Mm3h/zMtEdJSbU7yf02Zopy4lPkpnpnSp2M=,iv:a+0eBfAdKSGl5fhggiSbBpf/jCSNFb9I4nTexFxgnPA=,tag:mNauHY2chJhnfeM00LvpTg==,type:str]
    version: 3.13.3
