apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - credentials.sops.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - alerts.yaml

configMapGenerator:
  - name: grafana-dashboard-proxmox
    namespace: monitoring
    files:
      - proxmox.json=dashboards/proxmox.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
