# docker stack deploy --compose-file docker-compose.portainer.yml portainer
services:
  agent:
    image: portainer/agent:2.19.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.19.4
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - type: bind
        source: /mnt/Portainer
        target: /data
    networks:
      - agent_network
      - proxy
    deploy:
      labels:
        - "tunnel.enabled=true"
        - "tunnel.port=9000"
        - "tunnel.hostname=portainer.alexraskin.com"
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true
  proxy:
    external: true
    name: proxy