# docker stack deploy -c docker-compose.twizy.yml twizy --with-registry-auth
services:
  web:
    image: ghcr.io/alexraskin/twizy-web:${GIT_COMMIT_HASH:-latest}
    secrets:
      - r2_access_key
      - r2_secret_key
      - r2_endpoint
      - r2_bucket
    environment:
      - R2_ACCESS_KEY=/run/secrets/r2_access_key
      - R2_SECRET_KEY=/run/secrets/r2_secret_key
      - R2_ENDPOINT=/run/secrets/r2_endpoint
      - R2_BUCKET=/run/secrets/r2_bucket
    networks:
      - proxy
    deploy:
      labels:
        - "cloudflared.tunnel.enabled=true"
        - "cloudflared.tunnel.port=8080"
        - "cloudflared.tunnel.0.hostname=twizy.sh"
        - "cloudflared.tunnel.1.hostname=www.twizy.sh"
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy

secrets:
  r2_access_key:
    external: true
  r2_secret_key:
    external: true
  r2_endpoint:
    external: true
  r2_bucket:
    external: true
