apiVersion: v1
kind: Secret
metadata:
  name: lhbotgo-config
  namespace: lhbotgo
type: Opaque
stringData:
  bot-token: PASTE_DISCORD_BOT_TOKEN_HERE
  mongo-uri: mongodb://user:password@host:27017/?authSource=admin
  lhcloudy-id: "0"
  command-channel-ids: ""
