# docker stack deploy --compose-file docker-compose.lastfm.yml lastfm
services:
  api:
    image: ghcr.io/alexraskin/lastfm-now-playing:${GIT_COMMIT_HASH:-latest}
    networks:
      - proxy
    secrets:
      - lastfm-api-key
    environment:
      - LASTFM_API_KEY=/run/secrets/lastfm-api-key
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  proxy:
    external: true
    name: proxy

secrets:
  lastfm-api-key:
    external: true