services:
  telegraf:
    image: telegraf:1.25
    container_name: telegraf
    user: telegraf:995
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - metrics

networks:
  metrics:
    external: true