apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: "7.2.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
      interval: 24h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deploymentMode: SingleBinary
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false
    gateway:
      enabled: false
    minio:
      enabled: false
    loki:
      auth_enabled: false

      commonConfig:
        replication_factor: 1

      schemaConfig:
        configs:
          - from: "2026-08-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h

      limits_config:
        retention_period: 168h # 30 days
        reject_old_samples: true
        reject_old_samples_max_age: 168h

      compactor:
        retention_enabled: true
        delete_request_store: s3

      storage:
        type: s3
        bucketNames:
          chunks: loki
          ruler: loki
        s3:
          endpoint: ${R2_ENDPOINT}
          accessKeyId: ${R2_ACCESS_KEY_ID}
          secretAccessKey: ${R2_SECRET_ACCESS_KEY}
          region: auto
          s3ForcePathStyle: true
    singleBinary:
      replicas: 1
      extraArgs:
        - "-config.expand-env=true"
      extraEnvFrom:
        - secretRef:
            name: loki-r2
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi

      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 1Gi
