apiVersion: v1
kind: Secret
metadata:
  name: loki-r2
  namespace: logging
type: Opaque
stringData:
  R2_ACCESS_KEY_ID: PASTE_R2_ACCESS_KEY_ID_HERE
  R2_SECRET_ACCESS_KEY: PASTE_R2_SECRET_ACCESS_KEY_HERE
  R2_ENDPOINT: https://ACCOUNT_ID.r2.cloudflarestorage.com
