name: "Tailscale: deploy"

on:
  push:
    branches:
      - main
    paths:
      - "tailscale/**"
      - ".github/workflows/tailscale-deploy.yml"
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply (dangerous)"
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

concurrency:
  group: tailscale
  cancel-in-progress: false

jobs:
  terraform:
    name: "tailscale"
    runs-on: ubuntu-latest

    environment: tailscale
    defaults:
      run:
        working-directory: ./tailscale
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

      OCI_SDK_DEFAULT_RETRY_ENABLED: "true"

      TAILSCALE_OAUTH_CLIENT_ID: ${{ vars.TAILSCALE_OAUTH_CLIENT_ID }}
      TAILSCALE_AUDIENCE: ${{ vars.TAILSCALE_AUDIENCE }}

      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: "1.15"
          terraform_wrapper: false

      - name: Setup sops
        uses: nhedger/setup-sops@18e52f363488ed469d2e1855e542a1c651743bba # v3.0.0
        with:
          version: 3.13.3

      - name: Terraform Init
        run: ${{ github.workspace }}/scripts/tf.sh tailscale init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: ${{ github.workspace }}/scripts/tf.sh tailscale plan -out .planfile -input=false

      - name: Terraform Apply
        if: |
          (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
          (github.event_name == 'workflow_dispatch' && inputs.apply)
        run: ${{ github.workspace }}/scripts/tf.sh tailscale apply -auto-approve -input=false .planfile
